# Generated by Django 4.2.30 on 2026-04-08 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anonymous_code', models.CharField(max_length=20)),
                ('exam_subject_id', models.BigIntegerField()),
                ('difference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGradeLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_subject_id', models.BigIntegerField(unique=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CopyGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anonymous_code', models.CharField(max_length=20)),
                ('exam_subject_id', models.BigIntegerField()),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('correction_order', models.CharField(choices=[('FIRST', 'First'), ('SECOND', 'Second'), ('THIRD', 'Third')], max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_final', models.BooleanField(default=False)),
                ('corrector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copy_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anonymous_code', models.CharField(max_length=20)),
                ('exam_subject_id', models.BigIntegerField()),
                ('order', models.CharField(choices=[('FIRST', 'First'), ('SECOND', 'Second'), ('THIRD', 'Third')], max_length=10)),
                ('corrector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('anonymous_code', 'exam_subject_id', 'order')},
            },
        ),
    ]
