# Generated by Django 6.0.4 on 2026-04-14 23:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='correctionassignment',
            unique_together={('anonymous_code', 'exam_subject_id', 'corrector'), ('anonymous_code', 'exam_subject_id', 'order')},
        ),
    ]
