# Generated by Django 6.0.3 on 2026-03-12 13:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('building', models.CharField(blank=True, max_length=100)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{18}$', message='National ID must be 18 digits')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('PRESENT', 'Present'), ('ELIMINATED', 'Eliminated')], default='REGISTERED', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/')),
                ('national_id_file', models.FileField(blank=True, null=True, upload_to='candidate_documents/')),
                ('diploma_file', models.FileField(blank=True, null=True, upload_to='candidate_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_candidates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidates',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AnonymousCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_codes', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_code', to='api.candidate')),
            ],
            options={
                'db_table': 'anonymous_codes',
            },
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_file', models.FileField(upload_to='scans/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('qr_detected', models.BooleanField(default=False)),
                ('page_count', models.IntegerField(default=1)),
                ('anonymous_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='api.anonymouscode')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_copies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'copies',
                'db_table': 'copies',
            },
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField(blank=True)),
                ('attempt', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], default=1)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='api.copy')),
                ('corrector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'corrections',
                'ordering': ['copy', 'attempt'],
            },
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=5)),
                ('resolved', models.BooleanField(default=False)),
                ('third_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('coordinator_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('copy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancy', to='api.copy')),
                ('third_corrector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_discrepancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'discrepancies',
                'db_table': 'discrepancies',
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_sessions',
                'ordering': ['-year', '-date'],
            },
        ),
        migrations.CreateModel(
            name='Deliberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('decision', models.CharField(choices=[('ADMITTED', 'Admitted'), ('WAITLIST', 'Waitlist'), ('REJECTED', 'Rejected')], max_length=20)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', to='api.candidate')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', to='api.examsession')),
            ],
            options={
                'db_table': 'deliberations',
                'ordering': ['rank'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='exam_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='api.examsession'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='attendance_photos/')),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.candidate')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='api.examsession')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-marked_at'],
            },
        ),
        migrations.CreateModel(
            name='PVReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(upload_to='pv/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed', models.BooleanField(default=False)),
                ('signers', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pvs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pv_reports', to='api.examsession')),
            ],
            options={
                'db_table': 'pv_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('discrepancy_threshold', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('final_grade_rule', models.CharField(choices=[('AVERAGE', 'Average'), ('MEDIAN', 'Median'), ('THIRD', 'Third Corrector')], default='AVERAGE', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('LOCKED', 'Locked')], default='DRAFT', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=180, validators=[django.core.validators.MinValueValidator(30)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.examsession')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='api.room')),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['exam_session', 'scheduled_date'],
            },
        ),
        migrations.AddField(
            model_name='copy',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copies', to='api.subject'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('CFD_HEAD', 'CFD Head'), ('COORDINATOR', 'Coordinator'), ('CORRECTOR', 'Corrector'), ('SUPERVISOR', 'Supervisor'), ('JURY_MEMBER', 'Jury Member')], default='CORRECTOR', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('email_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('IMPORT', 'Import'), ('EXPORT', 'Export'), ('GENERATE_CODE', 'Generate Code'), ('UPLOAD_SCAN', 'Upload Scan'), ('MARK_ATTENDANCE', 'Mark Attendance'), ('SUBMIT_GRADE', 'Submit Grade'), ('RESOLVE_DISCREPANCY', 'Resolve Discrepancy'), ('CLOSE_SESSION', 'Close Session'), ('SIGN_PV', 'Sign PV'), ('ASSIGN_ROLE', 'Assign Role'), ('INVITE_USER', 'Invite User'), ('ACTIVATE_SUBJECT', 'Activate Subject'), ('LOCK_SUBJECT', 'Lock Subject'), ('REVEAL_IDENTITY', 'Reveal Identity')], max_length=50)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'permissions': [('can_view_audit_logs', 'Can view audit logs')],
                'indexes': [models.Index(fields=['user'], name='audit_logs_user_id_73c422_idx'), models.Index(fields=['action'], name='audit_logs_action_31f574_idx'), models.Index(fields=['object_type'], name='audit_logs_object__69dfc3_idx'), models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='anonymouscode',
            index=models.Index(fields=['code'], name='anonymous_c_code_0b1766_idx'),
        ),
        migrations.AddIndex(
            model_name='correction',
            index=models.Index(fields=['corrector'], name='corrections_correct_a21c57_idx'),
        ),
        migrations.AddIndex(
            model_name='correction',
            index=models.Index(fields=['submitted_at'], name='corrections_submitt_7bceb4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='correction',
            unique_together={('copy', 'attempt')},
        ),
        migrations.AddIndex(
            model_name='discrepancy',
            index=models.Index(fields=['resolved'], name='discrepanci_resolve_5b6ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['status'], name='exam_sessio_status_954ce7_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['year'], name='exam_sessio_year_c76dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='deliberation',
            index=models.Index(fields=['decision'], name='deliberatio_decisio_5a7ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='deliberation',
            index=models.Index(fields=['session'], name='deliberatio_session_7f6887_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliberation',
            unique_together={('candidate', 'session')},
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['status'], name='candidates_status_c98735_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['application_number'], name='candidates_applica_4445fd_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['national_id'], name='candidates_nationa_67ea90_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email'], name='candidates_email_32f680_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['exam_session'], name='candidates_exam_se_e11836_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['present'], name='attendance_present_daa1d4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['session'], name='attendance_session_4b3d35_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['candidate'], name='attendance_candida_48b929_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('candidate', 'session')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['status'], name='subjects_status_6bd3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['exam_session'], name='subjects_exam_se_53d152_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('exam_session', 'code')},
        ),
        migrations.AddIndex(
            model_name='copy',
            index=models.Index(fields=['anonymous_code'], name='copies_anonymo_75b3af_idx'),
        ),
        migrations.AddIndex(
            model_name='copy',
            index=models.Index(fields=['subject'], name='copies_subject_00a5d0_idx'),
        ),
        migrations.AddIndex(
            model_name='copy',
            index=models.Index(fields=['uploaded_at'], name='copies_uploade_0e744e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='copy',
            unique_together={('anonymous_code', 'subject')},
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='user_profil_role_fa03e1_idx'),
        ),
    ]
