# Generated by Django 6.0.3 on 2026-03-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('CFD_HEAD', 'CFD Head'), ('COORDINATOR', 'Coordinator'), ('CORRECTOR', 'Corrector'), ('SUPERVISOR', 'Supervisor'), ('JURY_PRESIDENT', 'Jury President'), ('JURY_MEMBER', 'Jury Member'), ('ANONYMITY_COMMISSION', 'Anonymity Commission')], default='CORRECTOR', max_length=20),
        ),
    ]
