# Generated by Django 6.0.3 on 2026-03-24 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_userprofile_role"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userprofile",
            name="user_profil_role_fa03e1_idx",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
