# Generated by Django 6.0.3 on 2026-03-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userprofile_user_profil_role_fa03e1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='incident_type',
            field=models.CharField(blank=True, choices=[('CHEATING', 'Cheating Attempt'), ('HEALTH', 'Health Issue'), ('DISTURBANCE', 'Disturbance'), ('LATE', 'Late Arrival'), ('OTHER', 'Other Incident')], max_length=20, null=True),
        ),
    ]
