# Generated by Django 6.0.3 on 2026-03-24 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("CFD_HEAD", "CFD Head"),
                            ("COORDINATOR", "Coordinator"),
                            ("CORRECTOR", "Corrector"),
                            ("SUPERVISOR", "Supervisor"),
                            ("JURY_PRESIDENT", "Jury President"),
                            ("JURY_MEMBER", "Jury Member"),
                            ("ANONYMITY_COMMISSION", "Anonymity Commission"),
                            ("CANDIDATE", "Candidate"),
                        ],
                        default="CANDIDATE",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "signature",
                    models.ImageField(blank=True, null=True, upload_to="signatures/"),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("must_change_password", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
                "indexes": [
                    models.Index(fields=["role"], name="user_profil_role_fa03e1_idx")
                ],
            },
        ),
    ]
