# Generated by Django 4.2.30 on 2026-04-08 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliberationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_session_id', models.BigIntegerField(unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliberations_closed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliberationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_id', models.BigIntegerField(blank=True, null=True)),
                ('anonymous_code', models.CharField(max_length=20)),
                ('weighted_average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rank', models.PositiveIntegerField()),
                ('outcome', models.CharField(choices=[('ADMITTED', 'Admitted'), ('WAITING_LIST', 'Waiting List'), ('REJECTED', 'Rejected')], max_length=20)),
                ('deliberation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='deliberation.deliberationrun')),
            ],
            options={
                'ordering': ['rank', 'id'],
                'unique_together': {('deliberation', 'rank')},
            },
        ),
    ]
