# Generated by Django 6.0.4 on 2026-04-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliberation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliberationrun',
            name='admission_threshold',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='deliberationrun',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliberationrun',
            name='waiting_list_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
