# Generated by Django 4.2.30 on 2026-04-08 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PVDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pv_type', models.CharField(choices=[('SUBJECT_CREATION', 'PV of Subject Creation'), ('SUBJECT_LOTTERY', 'PV of Subject Lottery'), ('ATTENDANCE', 'PV of Attendance'), ('ANONYMIZATION', 'PV of Anonymization'), ('CORRECTION', 'PV of Correction'), ('DELIBERATION', 'PV of Deliberation')], max_length=30)),
                ('exam_session_id', models.BigIntegerField()),
                ('document_identifier', models.CharField(max_length=64, unique=True)),
                ('file', models.FileField(upload_to='pv/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_pvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PVSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signer_name', models.CharField(max_length=255)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('pv_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='pv.pvdocument')),
                ('signer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pv_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
