# Generated by Django 6.0.4 on 2026-04-14 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='lottery_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lottery_selected_in', to='examinations.examsubject', verbose_name='Subject selected by lottery'),
        ),
    ]
