# Generated by Django 4.2.30 on 2026-04-08 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('candidate_id_encrypted', models.TextField()),
                ('exam_session_id', models.BigIntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExamCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='scans/')),
                ('uploaded_by_user_id', models.BigIntegerField(blank=True, null=True)),
                ('qr_detected_code', models.CharField(blank=True, max_length=64)),
                ('anonymous_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='anonymization.anonymouscode')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
