export const ROLES = {
  ADMIN: 'ADMIN',
  CFD_HEAD: 'CFD_HEAD',
  COORDINATOR: 'COORDINATOR',
  CORRECTOR: 'CORRECTOR',
  SUPERVISOR: 'SUPERVISOR',
  JURY_MEMBER: 'JURY_MEMBER',
}

export const PERMISSIONS = {
  // Candidates
  VIEW_CANDIDATES: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR],
  EDIT_CANDIDATES: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR],
  DELETE_CANDIDATES: [ROLES.ADMIN],
  IMPORT_CANDIDATES: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR],
  EXPORT_CANDIDATES: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR],

  // Sessions
  VIEW_SESSIONS: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR, ROLES.SUPERVISOR, ROLES.JURY_MEMBER],
  EDIT_SESSIONS: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR],
  DELETE_SESSIONS: [ROLES.ADMIN],

  // Subjects
  VIEW_SUBJECTS: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR, ROLES.CORRECTOR, ROLES.SUPERVISOR],
  EDIT_SUBJECTS: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR],
  ACTIVATE_SUBJECTS: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR],

  // Attendance
  VIEW_ATTENDANCE: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR, ROLES.SUPERVISOR],
  MARK_ATTENDANCE: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR, ROLES.SUPERVISOR],

  // Anonymization
  VIEW_ANONYMIZATION: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR],
  GENERATE_CODES: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR],

  // Correction
  VIEW_CORRECTIONS: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR, ROLES.CORRECTOR],
  SUBMIT_CORRECTIONS: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR, ROLES.CORRECTOR],

  // Discrepancies
  VIEW_DISCREPANCIES: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR],
  RESOLVE_DISCREPANCIES: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR],

  // Deliberation
  VIEW_DELIBERATION: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.JURY_MEMBER],
  CLOSE_DELIBERATION: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.JURY_MEMBER],

  // PV
  VIEW_PV: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR, ROLES.JURY_MEMBER],
  GENERATE_PV: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.COORDINATOR, ROLES.JURY_MEMBER],
  SIGN_PV: [ROLES.ADMIN, ROLES.CFD_HEAD, ROLES.JURY_MEMBER],

  // Admin
  VIEW_USERS: [ROLES.ADMIN],
  EDIT_USERS: [ROLES.ADMIN],
  VIEW_AUDIT: [ROLES.ADMIN],
  EDIT_SETTINGS: [ROLES.ADMIN],
}

export const hasPermission = (userRole, permission) => {
  if (!userRole || !permission) return false
  return PERMISSIONS[permission]?.includes(userRole) || false
}